apiVersion: v1
kind: PersistentVolume
metadata:
  name: theia-elevation-dem
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 32Gi
  nfs:
    path: /summer-argent-osug-04/theia/elevation-dem
    server: sum-osugdc-nas.ujf-grenoble.fr
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - bg
    - nolock
    - noatime
  volumeMode: Filesystem
